# Generated by Django 2.2.16 on 2022-02-11 07:02

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, help_text='Используйте следующий формат: <YYYY>', validators=[django.core.validators.MinValueValidator(1900, 'Выберите произведения изданные после 1900г.'), reviews.validators.validate_year], verbose_name='Год.'),
        ),
    ]
