# Generated by Django 2.2.16 on 2022-02-11 07:04

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220211_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, help_text='Используйте следующий формат: <YYYY>', validators=[reviews.validators.validate_year], verbose_name='Год.'),
        ),
    ]
