# Generated by Django 2.2.16 on 2022-02-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220207_1119'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='Unique constraint',
        ),
    ]
