# Generated by Django 2.2.16 on 2022-02-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220203_1842'),
        ('reviews', '0008_auto_20220204_0844'),
    ]

    operations = [
    ]
